# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac46d01633c63724ab90b84d51e0be0ed756ce1ca034961f62ec74156862d33ae7b98ac61dc62518e37d1c83a7ff6d21c99dd6ede9a69855afbd18b11b69ee4

test:
  secret_key_base: 2c8c5a69ca257cd838c174d97b9a3544ace57cefda6ddbee7fa624f0b426adb6f5a205c3d923a6e4f1326066ed6f3b15e779204ff3bfd6a4a2a6aed21b1484e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
